### ISSUE TITLE
Only one seeg.groovy file gets processed

### ISSUE THREAD

**Issue by gorshunovr** [att-comdev/cicd#13]
There is a bug in `superseed.sh` script: https://github.com/att-comdev/cicd/blob/930681976abaddef5ea496e35c0b4828b90fd171/cicd/SuperSeed/superseed.sh#L72-L75 https://github.com/att-comdev/cicd/blob/930681976abaddef5ea496e35c0b4828b90fd171/cicd/SuperSeed/superseed.sh#L37-L44
Only one (the last one) seed.groovy file is being copied and later gets processed in `Processing DSL script` part of the SuperSeed job in https://github.com/att-comdev/cicd/blob/930681976abaddef5ea496e35c0b4828b90fd171/cicd/SuperSeed/seed.groovy#L60-L64.

**Comment by nycmoma** [comment]
it is 'not a bug', it's a limitation of CI process "one job per commit" which was described in the development workflow (AFAIR).  to extend it - you have to rewrite the pipeline.

**Comment by gorshunovr** [comment]
Mike, thank you for your reply! I hope you are doing well.
So that's just a workflow limitation. I think I know how to make it parse all Jenkinsfiles, and will submit a patch to the pipeline.
